### ISSUE TITLE
Cannot find TouhouCV/Graphical/power.png

### ISSUE THREAD

**Issue by actumn** [Netdex/TouhouCV#3]
Can you upload it?

**Comment by Netdex** [comment]
It's been a while since I've worked on this project!
Here's a zip file containing the contents of Graphical:
[Graphical.zip](https://github.com/Netdex/TouhouCV/files/2499539/Graphical.zip)

Please let me know if you have any more questions.

**Comment by actumn** [comment]
Thank you so much. :)
